version: "3.8"

services:
    mysql:
        image: mysql:8.0
        container_name: customer-mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: customer_db
            MYSQL_USER: customer_user
            MYSQL_PASSWORD: customer_password
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        networks:
            - backend-net
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 30s

    customer-app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: customer-app
        depends_on:
            mysql:
                condition: service_healthy
        env_file:
            - .env
        environment:
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_USERNAME=customer_user
            - DB_PASSWORD=customer_password
            - DB_DATABASE=customer_db
        ports:
            - "3000:3000"
        restart: always
        networks:
            - backend-net

volumes:
    mysql_data:

networks:
    backend-net:
        driver: bridge
