version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: customer-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: customer_db
      MYSQL_USER: customer_user
      MYSQL_PASSWORD: customer_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - backend-net

  customer-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: customer-app
    depends_on:
      - mysql
    env_file:
      - .env
    ports:
      - "3000:3000"
    restart: always
    networks:
      - backend-net

volumes:
  mysql_data:

networks:
  backend-net:
    driver: bridge
